apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstoneapp
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: capstoneapp
    spec:
      containers:
      - name: capstoneapp
        image: mohamed992/capstoneapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: default-port